### ISSUE TITLE
Ensure dependencies are installed

### ISSUE THREAD

**Issue by denics** [totaldebug/ansible-role-hassio#2]
When the role is ensuring dependencies are installed it looks for python-docker while in raspbianos bullseye the package is called python3-docker, hence it fails

## Expected behavior

The role should take into account the version of the software, we are slowly moving away from python2

## Current behavior

The role stops with an error

## Steps to reproduce

1. Try to launch the role on a rasbianos bullseye
2. See error

**Comment by marksie1988** [comment]
This role is currently only designed to work with Debian and hasn't been tested with any other operating system as Debian is the only supported os. 

If using a raspberry pi I recommend using hassos instead.

**Comment by denics** [comment]
I wanted to avoid hassos because of its design. i.e. you cannot use camera or sensehat anymore :( I will try to make it work properly and maybe open a MR ok?

**Comment by marksie1988** [comment]
Sure that would be good if you have the time to take a look. I wasn't aware they had stopped supporting that!

**Comment by MelOuwensPXL** [comment]
This problem still exists on Debian 11, not only on Raspbian
The package `python-docker` does not exist and has presumably been replaced by `python3-docker` after Debian 10 Buster https://packages.debian.org/buster/python-docker
